name: CI

on:
  push:
    branches: [ main, "feature/**", "tasks/**" ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Optional Postgres driver for Supabase/Postgres
          pip install "psycopg[binary]"
      - name: Lint
        run: |
          pip install flake8
          flake8
      - name: Migrate database (if DATABASE_URL provided)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [ -n "${DATABASE_URL}" ]; then
            python -m src.database.init_db
          else
            echo "Skipping migration (no DATABASE_URL)"
          fi
      - name: Run tests
        run: |
          pip install pytest
          pytest -q
      - name: Run pipeline (if DATABASE_URL provided)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [ -n "${DATABASE_URL}" ]; then
            python -m src.cli pipeline --config config/feeds.yaml
          else
            echo "Skipping pipeline (no DATABASE_URL)"
          fi
