name: Scheduled Pipeline

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    concurrency:
      group: scheduled-pipeline
      cancel-in-progress: false
    env:
      # Helpful default UA for some RSS feeds (can be overridden as a secret/repo var)
      T4L_USER_AGENT: T4L-End2End/1.0 (+https://github.com/BigSlikTobi/T4L_End2End)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Skip raw DB pipeline
        run: |
          echo "Skipping raw Postgres pipeline; use simple-supabase.yml instead."
      - name: Summarize
        run: |
          echo "Pipeline completed at $(date -u)."
